// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorContainer': string;
  'modalContent': string;
  'note': string;
  'padded': string;
  'section': string;
  'warning': string;
}
declare var cssExports: CssExports;
export = cssExports;
