// source: riva_asr.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf')
var goog = jspb
var global = Function('return this')()

var riva_audio_pb = require('./riva_audio_pb.js')
goog.object.extend(proto, riva_audio_pb)
goog.exportSymbol('proto.nvidia.riva.asr.RecognitionConfig', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.RecognizeRequest', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.RecognizeResponse', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.SpeechContext', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.SpeechRecognitionAlternative', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.SpeechRecognitionResult', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.StreamingRecognitionConfig', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.StreamingRecognitionResult', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.StreamingRecognizeRequest', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.StreamingRecognizeRequest.StreamingRequestCase', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.StreamingRecognizeResponse', null, global)
goog.exportSymbol('proto.nvidia.riva.asr.WordInfo', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.RecognizeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.nvidia.riva.asr.RecognizeRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.RecognizeRequest.displayName = 'proto.nvidia.riva.asr.RecognizeRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.nvidia.riva.asr.StreamingRecognizeRequest.oneofGroups_)
}
goog.inherits(proto.nvidia.riva.asr.StreamingRecognizeRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.StreamingRecognizeRequest.displayName = 'proto.nvidia.riva.asr.StreamingRecognizeRequest'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.RecognitionConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nvidia.riva.asr.RecognitionConfig.repeatedFields_, null)
}
goog.inherits(proto.nvidia.riva.asr.RecognitionConfig, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.RecognitionConfig.displayName = 'proto.nvidia.riva.asr.RecognitionConfig'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.nvidia.riva.asr.StreamingRecognitionConfig, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.StreamingRecognitionConfig.displayName = 'proto.nvidia.riva.asr.StreamingRecognitionConfig'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.SpeechContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nvidia.riva.asr.SpeechContext.repeatedFields_, null)
}
goog.inherits(proto.nvidia.riva.asr.SpeechContext, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.SpeechContext.displayName = 'proto.nvidia.riva.asr.SpeechContext'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.RecognizeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nvidia.riva.asr.RecognizeResponse.repeatedFields_, null)
}
goog.inherits(proto.nvidia.riva.asr.RecognizeResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.RecognizeResponse.displayName = 'proto.nvidia.riva.asr.RecognizeResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.SpeechRecognitionResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nvidia.riva.asr.SpeechRecognitionResult.repeatedFields_, null)
}
goog.inherits(proto.nvidia.riva.asr.SpeechRecognitionResult, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.SpeechRecognitionResult.displayName = 'proto.nvidia.riva.asr.SpeechRecognitionResult'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.nvidia.riva.asr.SpeechRecognitionAlternative.repeatedFields_,
    null
  )
}
goog.inherits(proto.nvidia.riva.asr.SpeechRecognitionAlternative, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.SpeechRecognitionAlternative.displayName = 'proto.nvidia.riva.asr.SpeechRecognitionAlternative'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.WordInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.nvidia.riva.asr.WordInfo, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.WordInfo.displayName = 'proto.nvidia.riva.asr.WordInfo'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nvidia.riva.asr.StreamingRecognizeResponse.repeatedFields_, null)
}
goog.inherits(proto.nvidia.riva.asr.StreamingRecognizeResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.StreamingRecognizeResponse.displayName = 'proto.nvidia.riva.asr.StreamingRecognizeResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nvidia.riva.asr.StreamingRecognitionResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nvidia.riva.asr.StreamingRecognitionResult.repeatedFields_, null)
}
goog.inherits(proto.nvidia.riva.asr.StreamingRecognitionResult, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nvidia.riva.asr.StreamingRecognitionResult.displayName = 'proto.nvidia.riva.asr.StreamingRecognitionResult'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.RecognizeRequest.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.RecognizeRequest.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.RecognizeRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.RecognizeRequest.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        config: (f = msg.getConfig()) && proto.nvidia.riva.asr.RecognitionConfig.toObject(includeInstance, f),
        audio: msg.getAudio_asB64()
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.RecognizeRequest}
 */
proto.nvidia.riva.asr.RecognizeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.RecognizeRequest()
  return proto.nvidia.riva.asr.RecognizeRequest.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.RecognizeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.RecognizeRequest}
 */
proto.nvidia.riva.asr.RecognizeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.RecognitionConfig()
        reader.readMessage(value, proto.nvidia.riva.asr.RecognitionConfig.deserializeBinaryFromReader)
        msg.setConfig(value)
        break
      case 2:
        var value = /** @type {!Uint8Array} */ (reader.readBytes())
        msg.setAudio(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.RecognizeRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.RecognizeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.RecognizeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getConfig()
  if (f != null) {
    writer.writeMessage(1, f, proto.nvidia.riva.asr.RecognitionConfig.serializeBinaryToWriter)
  }
  f = message.getAudio_asU8()
  if (f.length > 0) {
    writer.writeBytes(2, f)
  }
}

/**
 * optional RecognitionConfig config = 1;
 * @return {?proto.nvidia.riva.asr.RecognitionConfig}
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.getConfig = function() {
  return /** @type{?proto.nvidia.riva.asr.RecognitionConfig} */ (jspb.Message.getWrapperField(
    this,
    proto.nvidia.riva.asr.RecognitionConfig,
    1
  ))
}

/**
 * @param {?proto.nvidia.riva.asr.RecognitionConfig|undefined} value
 * @return {!proto.nvidia.riva.asr.RecognizeRequest} returns this
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.setConfig = function(value) {
  return jspb.Message.setWrapperField(this, 1, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.nvidia.riva.asr.RecognizeRequest} returns this
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.clearConfig = function() {
  return this.setConfig(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional bytes audio = 2;
 * @return {!(string|Uint8Array)}
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.getAudio = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/**
 * optional bytes audio = 2;
 * This is a type-conversion wrapper around `getAudio()`
 * @return {string}
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.getAudio_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(this.getAudio()))
}

/**
 * optional bytes audio = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAudio()`
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.getAudio_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getAudio()))
}

/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.nvidia.riva.asr.RecognizeRequest} returns this
 */
proto.nvidia.riva.asr.RecognizeRequest.prototype.setAudio = function(value) {
  return jspb.Message.setProto3BytesField(this, 2, value)
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.oneofGroups_ = [[1, 2]]

/**
 * @enum {number}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.StreamingRequestCase = {
  STREAMING_REQUEST_NOT_SET: 0,
  STREAMING_CONFIG: 1,
  AUDIO_CONTENT: 2
}

/**
 * @return {proto.nvidia.riva.asr.StreamingRecognizeRequest.StreamingRequestCase}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.getStreamingRequestCase = function() {
  return /** @type {proto.nvidia.riva.asr.StreamingRecognizeRequest.StreamingRequestCase} */ (jspb.Message.computeOneofCase(
    this,
    proto.nvidia.riva.asr.StreamingRecognizeRequest.oneofGroups_[0]
  ))
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.StreamingRecognizeRequest.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.StreamingRecognizeRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.StreamingRecognizeRequest.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        streamingConfig:
          (f = msg.getStreamingConfig()) &&
          proto.nvidia.riva.asr.StreamingRecognitionConfig.toObject(includeInstance, f),
        audioContent: msg.getAudioContent_asB64()
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeRequest}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.StreamingRecognizeRequest()
  return proto.nvidia.riva.asr.StreamingRecognizeRequest.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.StreamingRecognizeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeRequest}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.StreamingRecognitionConfig()
        reader.readMessage(value, proto.nvidia.riva.asr.StreamingRecognitionConfig.deserializeBinaryFromReader)
        msg.setStreamingConfig(value)
        break
      case 2:
        var value = /** @type {!Uint8Array} */ (reader.readBytes())
        msg.setAudioContent(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.StreamingRecognizeRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.StreamingRecognizeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getStreamingConfig()
  if (f != null) {
    writer.writeMessage(1, f, proto.nvidia.riva.asr.StreamingRecognitionConfig.serializeBinaryToWriter)
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2))
  if (f != null) {
    writer.writeBytes(2, f)
  }
}

/**
 * optional StreamingRecognitionConfig streaming_config = 1;
 * @return {?proto.nvidia.riva.asr.StreamingRecognitionConfig}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.getStreamingConfig = function() {
  return /** @type{?proto.nvidia.riva.asr.StreamingRecognitionConfig} */ (jspb.Message.getWrapperField(
    this,
    proto.nvidia.riva.asr.StreamingRecognitionConfig,
    1
  ))
}

/**
 * @param {?proto.nvidia.riva.asr.StreamingRecognitionConfig|undefined} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeRequest} returns this
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.setStreamingConfig = function(value) {
  return jspb.Message.setOneofWrapperField(
    this,
    1,
    proto.nvidia.riva.asr.StreamingRecognizeRequest.oneofGroups_[0],
    value
  )
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeRequest} returns this
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.clearStreamingConfig = function() {
  return this.setStreamingConfig(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.hasStreamingConfig = function() {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional bytes audio_content = 2;
 * @return {!(string|Uint8Array)}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.getAudioContent = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ''))
}

/**
 * optional bytes audio_content = 2;
 * This is a type-conversion wrapper around `getAudioContent()`
 * @return {string}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.getAudioContent_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(this.getAudioContent()))
}

/**
 * optional bytes audio_content = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getAudioContent()`
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.getAudioContent_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getAudioContent()))
}

/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeRequest} returns this
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.setAudioContent = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.nvidia.riva.asr.StreamingRecognizeRequest.oneofGroups_[0], value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeRequest} returns this
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.clearAudioContent = function() {
  return jspb.Message.setOneofField(this, 2, proto.nvidia.riva.asr.StreamingRecognizeRequest.oneofGroups_[0], undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nvidia.riva.asr.StreamingRecognizeRequest.prototype.hasAudioContent = function() {
  return jspb.Message.getField(this, 2) != null
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.RecognitionConfig.repeatedFields_ = [6]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.RecognitionConfig.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.RecognitionConfig.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.RecognitionConfig} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.RecognitionConfig.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        encoding: jspb.Message.getFieldWithDefault(msg, 1, 0),
        sampleRateHertz: jspb.Message.getFieldWithDefault(msg, 2, 0),
        languageCode: jspb.Message.getFieldWithDefault(msg, 3, ''),
        maxAlternatives: jspb.Message.getFieldWithDefault(msg, 4, 0),
        speechContextsList: jspb.Message.toObjectList(
          msg.getSpeechContextsList(),
          proto.nvidia.riva.asr.SpeechContext.toObject,
          includeInstance
        ),
        audioChannelCount: jspb.Message.getFieldWithDefault(msg, 7, 0),
        enableWordTimeOffsets: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
        enableAutomaticPunctuation: jspb.Message.getBooleanFieldWithDefault(msg, 11, false),
        enableSeparateRecognitionPerChannel: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
        model: jspb.Message.getFieldWithDefault(msg, 13, ''),
        verbatimTranscripts: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
        customConfigurationMap: (f = msg.getCustomConfigurationMap()) ? f.toObject(includeInstance, undefined) : []
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.RecognitionConfig}
 */
proto.nvidia.riva.asr.RecognitionConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.RecognitionConfig()
  return proto.nvidia.riva.asr.RecognitionConfig.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.RecognitionConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.RecognitionConfig}
 */
proto.nvidia.riva.asr.RecognitionConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {!proto.nvidia.riva.AudioEncoding} */ (reader.readEnum())
        msg.setEncoding(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setSampleRateHertz(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setLanguageCode(value)
        break
      case 4:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setMaxAlternatives(value)
        break
      case 6:
        var value = new proto.nvidia.riva.asr.SpeechContext()
        reader.readMessage(value, proto.nvidia.riva.asr.SpeechContext.deserializeBinaryFromReader)
        msg.addSpeechContexts(value)
        break
      case 7:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setAudioChannelCount(value)
        break
      case 8:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setEnableWordTimeOffsets(value)
        break
      case 11:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setEnableAutomaticPunctuation(value)
        break
      case 12:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setEnableSeparateRecognitionPerChannel(value)
        break
      case 13:
        var value = /** @type {string} */ (reader.readString())
        msg.setModel(value)
        break
      case 14:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setVerbatimTranscripts(value)
        break
      case 24:
        var value = msg.getCustomConfigurationMap()
        reader.readMessage(value, function(message, reader) {
          jspb.Map.deserializeBinary(
            message,
            reader,
            jspb.BinaryReader.prototype.readString,
            jspb.BinaryReader.prototype.readString,
            null,
            '',
            ''
          )
        })
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.RecognitionConfig.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.RecognitionConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.RecognitionConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getEncoding()
  if (f !== 0.0) {
    writer.writeEnum(1, f)
  }
  f = message.getSampleRateHertz()
  if (f !== 0) {
    writer.writeInt32(2, f)
  }
  f = message.getLanguageCode()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
  f = message.getMaxAlternatives()
  if (f !== 0) {
    writer.writeInt32(4, f)
  }
  f = message.getSpeechContextsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(6, f, proto.nvidia.riva.asr.SpeechContext.serializeBinaryToWriter)
  }
  f = message.getAudioChannelCount()
  if (f !== 0) {
    writer.writeInt32(7, f)
  }
  f = message.getEnableWordTimeOffsets()
  if (f) {
    writer.writeBool(8, f)
  }
  f = message.getEnableAutomaticPunctuation()
  if (f) {
    writer.writeBool(11, f)
  }
  f = message.getEnableSeparateRecognitionPerChannel()
  if (f) {
    writer.writeBool(12, f)
  }
  f = message.getModel()
  if (f.length > 0) {
    writer.writeString(13, f)
  }
  f = message.getVerbatimTranscripts()
  if (f) {
    writer.writeBool(14, f)
  }
  f = message.getCustomConfigurationMap(true)
  if (f && f.getLength() > 0) {
    f.serializeBinary(24, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString)
  }
}

/**
 * optional nvidia.riva.AudioEncoding encoding = 1;
 * @return {!proto.nvidia.riva.AudioEncoding}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getEncoding = function() {
  return /** @type {!proto.nvidia.riva.AudioEncoding} */ (jspb.Message.getFieldWithDefault(this, 1, 0))
}

/**
 * @param {!proto.nvidia.riva.AudioEncoding} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setEncoding = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value)
}

/**
 * optional int32 sample_rate_hertz = 2;
 * @return {number}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getSampleRateHertz = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setSampleRateHertz = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value)
}

/**
 * optional string language_code = 3;
 * @return {string}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/**
 * @param {string} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setLanguageCode = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * optional int32 max_alternatives = 4;
 * @return {number}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getMaxAlternatives = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setMaxAlternatives = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value)
}

/**
 * repeated SpeechContext speech_contexts = 6;
 * @return {!Array<!proto.nvidia.riva.asr.SpeechContext>}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getSpeechContextsList = function() {
  return /** @type{!Array<!proto.nvidia.riva.asr.SpeechContext>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.nvidia.riva.asr.SpeechContext,
    6
  ))
}

/**
 * @param {!Array<!proto.nvidia.riva.asr.SpeechContext>} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setSpeechContextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value)
}

/**
 * @param {!proto.nvidia.riva.asr.SpeechContext=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.SpeechContext}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.addSpeechContexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.nvidia.riva.asr.SpeechContext, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.clearSpeechContextsList = function() {
  return this.setSpeechContextsList([])
}

/**
 * optional int32 audio_channel_count = 7;
 * @return {number}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getAudioChannelCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setAudioChannelCount = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value)
}

/**
 * optional bool enable_word_time_offsets = 8;
 * @return {boolean}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getEnableWordTimeOffsets = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false))
}

/**
 * @param {boolean} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setEnableWordTimeOffsets = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value)
}

/**
 * optional bool enable_automatic_punctuation = 11;
 * @return {boolean}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getEnableAutomaticPunctuation = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 11, false))
}

/**
 * @param {boolean} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setEnableAutomaticPunctuation = function(value) {
  return jspb.Message.setProto3BooleanField(this, 11, value)
}

/**
 * optional bool enable_separate_recognition_per_channel = 12;
 * @return {boolean}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getEnableSeparateRecognitionPerChannel = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false))
}

/**
 * @param {boolean} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setEnableSeparateRecognitionPerChannel = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value)
}

/**
 * optional string model = 13;
 * @return {string}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ''))
}

/**
 * @param {string} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setModel = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value)
}

/**
 * optional bool verbatim_transcripts = 14;
 * @return {boolean}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getVerbatimTranscripts = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false))
}

/**
 * @param {boolean} value
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.setVerbatimTranscripts = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value)
}

/**
 * map<string, string> custom_configuration = 24;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.getCustomConfigurationMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (jspb.Message.getMapField(this, 24, opt_noLazyCreate, null))
}

/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.nvidia.riva.asr.RecognitionConfig} returns this
 */
proto.nvidia.riva.asr.RecognitionConfig.prototype.clearCustomConfigurationMap = function() {
  this.getCustomConfigurationMap().clear()
  return this
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.StreamingRecognitionConfig.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.StreamingRecognitionConfig} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.StreamingRecognitionConfig.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        config: (f = msg.getConfig()) && proto.nvidia.riva.asr.RecognitionConfig.toObject(includeInstance, f),
        interimResults: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionConfig}
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.StreamingRecognitionConfig()
  return proto.nvidia.riva.asr.StreamingRecognitionConfig.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.StreamingRecognitionConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionConfig}
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.RecognitionConfig()
        reader.readMessage(value, proto.nvidia.riva.asr.RecognitionConfig.deserializeBinaryFromReader)
        msg.setConfig(value)
        break
      case 2:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setInterimResults(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.StreamingRecognitionConfig.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.StreamingRecognitionConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getConfig()
  if (f != null) {
    writer.writeMessage(1, f, proto.nvidia.riva.asr.RecognitionConfig.serializeBinaryToWriter)
  }
  f = message.getInterimResults()
  if (f) {
    writer.writeBool(2, f)
  }
}

/**
 * optional RecognitionConfig config = 1;
 * @return {?proto.nvidia.riva.asr.RecognitionConfig}
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.getConfig = function() {
  return /** @type{?proto.nvidia.riva.asr.RecognitionConfig} */ (jspb.Message.getWrapperField(
    this,
    proto.nvidia.riva.asr.RecognitionConfig,
    1
  ))
}

/**
 * @param {?proto.nvidia.riva.asr.RecognitionConfig|undefined} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionConfig} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.setConfig = function(value) {
  return jspb.Message.setWrapperField(this, 1, value)
}

/**
 * Clears the message field making it undefined.
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionConfig} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.clearConfig = function() {
  return this.setConfig(undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.hasConfig = function() {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional bool interim_results = 2;
 * @return {boolean}
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.getInterimResults = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false))
}

/**
 * @param {boolean} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionConfig} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionConfig.prototype.setInterimResults = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.SpeechContext.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.SpeechContext.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.SpeechContext.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.SpeechContext} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.SpeechContext.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        phrasesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
        boost: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.SpeechContext}
 */
proto.nvidia.riva.asr.SpeechContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.SpeechContext()
  return proto.nvidia.riva.asr.SpeechContext.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.SpeechContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.SpeechContext}
 */
proto.nvidia.riva.asr.SpeechContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.addPhrases(value)
        break
      case 4:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setBoost(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.SpeechContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.SpeechContext.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.SpeechContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.SpeechContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getPhrasesList()
  if (f.length > 0) {
    writer.writeRepeatedString(1, f)
  }
  f = message.getBoost()
  if (f !== 0.0) {
    writer.writeFloat(4, f)
  }
}

/**
 * repeated string phrases = 1;
 * @return {!Array<string>}
 */
proto.nvidia.riva.asr.SpeechContext.prototype.getPhrasesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1))
}

/**
 * @param {!Array<string>} value
 * @return {!proto.nvidia.riva.asr.SpeechContext} returns this
 */
proto.nvidia.riva.asr.SpeechContext.prototype.setPhrasesList = function(value) {
  return jspb.Message.setField(this, 1, value || [])
}

/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.SpeechContext} returns this
 */
proto.nvidia.riva.asr.SpeechContext.prototype.addPhrases = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.SpeechContext} returns this
 */
proto.nvidia.riva.asr.SpeechContext.prototype.clearPhrasesList = function() {
  return this.setPhrasesList([])
}

/**
 * optional float boost = 4;
 * @return {number}
 */
proto.nvidia.riva.asr.SpeechContext.prototype.getBoost = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.SpeechContext} returns this
 */
proto.nvidia.riva.asr.SpeechContext.prototype.setBoost = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.RecognizeResponse.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.RecognizeResponse.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.RecognizeResponse.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.RecognizeResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.RecognizeResponse.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        resultsList: jspb.Message.toObjectList(
          msg.getResultsList(),
          proto.nvidia.riva.asr.SpeechRecognitionResult.toObject,
          includeInstance
        )
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.RecognizeResponse}
 */
proto.nvidia.riva.asr.RecognizeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.RecognizeResponse()
  return proto.nvidia.riva.asr.RecognizeResponse.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.RecognizeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.RecognizeResponse}
 */
proto.nvidia.riva.asr.RecognizeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.SpeechRecognitionResult()
        reader.readMessage(value, proto.nvidia.riva.asr.SpeechRecognitionResult.deserializeBinaryFromReader)
        msg.addResults(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.RecognizeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.RecognizeResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.RecognizeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.RecognizeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getResultsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(1, f, proto.nvidia.riva.asr.SpeechRecognitionResult.serializeBinaryToWriter)
  }
}

/**
 * repeated SpeechRecognitionResult results = 1;
 * @return {!Array<!proto.nvidia.riva.asr.SpeechRecognitionResult>}
 */
proto.nvidia.riva.asr.RecognizeResponse.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.nvidia.riva.asr.SpeechRecognitionResult>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.nvidia.riva.asr.SpeechRecognitionResult,
    1
  ))
}

/**
 * @param {!Array<!proto.nvidia.riva.asr.SpeechRecognitionResult>} value
 * @return {!proto.nvidia.riva.asr.RecognizeResponse} returns this
 */
proto.nvidia.riva.asr.RecognizeResponse.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult}
 */
proto.nvidia.riva.asr.RecognizeResponse.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.nvidia.riva.asr.SpeechRecognitionResult,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.RecognizeResponse} returns this
 */
proto.nvidia.riva.asr.RecognizeResponse.prototype.clearResultsList = function() {
  return this.setResultsList([])
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.SpeechRecognitionResult.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.SpeechRecognitionResult} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.SpeechRecognitionResult.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        alternativesList: jspb.Message.toObjectList(
          msg.getAlternativesList(),
          proto.nvidia.riva.asr.SpeechRecognitionAlternative.toObject,
          includeInstance
        ),
        channelTag: jspb.Message.getFieldWithDefault(msg, 2, 0),
        audioProcessed: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.SpeechRecognitionResult()
  return proto.nvidia.riva.asr.SpeechRecognitionResult.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.SpeechRecognitionAlternative()
        reader.readMessage(value, proto.nvidia.riva.asr.SpeechRecognitionAlternative.deserializeBinaryFromReader)
        msg.addAlternatives(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setChannelTag(value)
        break
      case 3:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setAudioProcessed(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.SpeechRecognitionResult.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getAlternativesList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(1, f, proto.nvidia.riva.asr.SpeechRecognitionAlternative.serializeBinaryToWriter)
  }
  f = message.getChannelTag()
  if (f !== 0) {
    writer.writeInt32(2, f)
  }
  f = message.getAudioProcessed()
  if (f !== 0.0) {
    writer.writeFloat(3, f)
  }
}

/**
 * repeated SpeechRecognitionAlternative alternatives = 1;
 * @return {!Array<!proto.nvidia.riva.asr.SpeechRecognitionAlternative>}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.getAlternativesList = function() {
  return /** @type{!Array<!proto.nvidia.riva.asr.SpeechRecognitionAlternative>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.nvidia.riva.asr.SpeechRecognitionAlternative,
    1
  ))
}

/**
 * @param {!Array<!proto.nvidia.riva.asr.SpeechRecognitionAlternative>} value
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.setAlternativesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionAlternative=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.addAlternatives = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.nvidia.riva.asr.SpeechRecognitionAlternative,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.clearAlternativesList = function() {
  return this.setAlternativesList([])
}

/**
 * optional int32 channel_tag = 2;
 * @return {number}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.getChannelTag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.setChannelTag = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value)
}

/**
 * optional float audio_processed = 3;
 * @return {number}
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.getAudioProcessed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionResult} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionResult.prototype.setAudioProcessed = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.repeatedFields_ = [3]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.SpeechRecognitionAlternative.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.SpeechRecognitionAlternative.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        transcript: jspb.Message.getFieldWithDefault(msg, 1, ''),
        confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        wordsList: jspb.Message.toObjectList(
          msg.getWordsList(),
          proto.nvidia.riva.asr.WordInfo.toObject,
          includeInstance
        )
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.SpeechRecognitionAlternative()
  return proto.nvidia.riva.asr.SpeechRecognitionAlternative.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setTranscript(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setConfidence(value)
        break
      case 3:
        var value = new proto.nvidia.riva.asr.WordInfo()
        reader.readMessage(value, proto.nvidia.riva.asr.WordInfo.deserializeBinaryFromReader)
        msg.addWords(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.SpeechRecognitionAlternative.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getTranscript()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
  f = message.getConfidence()
  if (f !== 0.0) {
    writer.writeFloat(2, f)
  }
  f = message.getWordsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(3, f, proto.nvidia.riva.asr.WordInfo.serializeBinaryToWriter)
  }
}

/**
 * optional string transcript = 1;
 * @return {string}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.getTranscript = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.setTranscript = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * optional float confidence = 2;
 * @return {number}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value)
}

/**
 * repeated WordInfo words = 3;
 * @return {!Array<!proto.nvidia.riva.asr.WordInfo>}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.getWordsList = function() {
  return /** @type{!Array<!proto.nvidia.riva.asr.WordInfo>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.nvidia.riva.asr.WordInfo,
    3
  ))
}

/**
 * @param {!Array<!proto.nvidia.riva.asr.WordInfo>} value
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.setWordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value)
}

/**
 * @param {!proto.nvidia.riva.asr.WordInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.WordInfo}
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.addWords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.nvidia.riva.asr.WordInfo, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative} returns this
 */
proto.nvidia.riva.asr.SpeechRecognitionAlternative.prototype.clearWordsList = function() {
  return this.setWordsList([])
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.WordInfo.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.WordInfo.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.WordInfo} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.WordInfo.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        startTime: jspb.Message.getFieldWithDefault(msg, 1, 0),
        endTime: jspb.Message.getFieldWithDefault(msg, 2, 0),
        word: jspb.Message.getFieldWithDefault(msg, 3, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.WordInfo}
 */
proto.nvidia.riva.asr.WordInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.WordInfo()
  return proto.nvidia.riva.asr.WordInfo.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.WordInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.WordInfo}
 */
proto.nvidia.riva.asr.WordInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setStartTime(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setEndTime(value)
        break
      case 3:
        var value = /** @type {string} */ (reader.readString())
        msg.setWord(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.WordInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.WordInfo.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.WordInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.WordInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getStartTime()
  if (f !== 0) {
    writer.writeInt32(1, f)
  }
  f = message.getEndTime()
  if (f !== 0) {
    writer.writeInt32(2, f)
  }
  f = message.getWord()
  if (f.length > 0) {
    writer.writeString(3, f)
  }
}

/**
 * optional int32 start_time = 1;
 * @return {number}
 */
proto.nvidia.riva.asr.WordInfo.prototype.getStartTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.WordInfo} returns this
 */
proto.nvidia.riva.asr.WordInfo.prototype.setStartTime = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional int32 end_time = 2;
 * @return {number}
 */
proto.nvidia.riva.asr.WordInfo.prototype.getEndTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.WordInfo} returns this
 */
proto.nvidia.riva.asr.WordInfo.prototype.setEndTime = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value)
}

/**
 * optional string word = 3;
 * @return {string}
 */
proto.nvidia.riva.asr.WordInfo.prototype.getWord = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''))
}

/**
 * @param {string} value
 * @return {!proto.nvidia.riva.asr.WordInfo} returns this
 */
proto.nvidia.riva.asr.WordInfo.prototype.setWord = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.StreamingRecognizeResponse.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.StreamingRecognizeResponse.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.StreamingRecognizeResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.StreamingRecognizeResponse.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        resultsList: jspb.Message.toObjectList(
          msg.getResultsList(),
          proto.nvidia.riva.asr.StreamingRecognitionResult.toObject,
          includeInstance
        )
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeResponse}
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.StreamingRecognizeResponse()
  return proto.nvidia.riva.asr.StreamingRecognizeResponse.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.StreamingRecognizeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeResponse}
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.StreamingRecognitionResult()
        reader.readMessage(value, proto.nvidia.riva.asr.StreamingRecognitionResult.deserializeBinaryFromReader)
        msg.addResults(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.StreamingRecognizeResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.StreamingRecognizeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getResultsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(1, f, proto.nvidia.riva.asr.StreamingRecognitionResult.serializeBinaryToWriter)
  }
}

/**
 * repeated StreamingRecognitionResult results = 1;
 * @return {!Array<!proto.nvidia.riva.asr.StreamingRecognitionResult>}
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.nvidia.riva.asr.StreamingRecognitionResult>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.nvidia.riva.asr.StreamingRecognitionResult,
    1
  ))
}

/**
 * @param {!Array<!proto.nvidia.riva.asr.StreamingRecognitionResult>} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeResponse} returns this
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.nvidia.riva.asr.StreamingRecognitionResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult}
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.nvidia.riva.asr.StreamingRecognitionResult,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.StreamingRecognizeResponse} returns this
 */
proto.nvidia.riva.asr.StreamingRecognizeResponse.prototype.clearResultsList = function() {
  return this.setResultsList([])
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.toObject = function(opt_includeInstance) {
    return proto.nvidia.riva.asr.StreamingRecognitionResult.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.nvidia.riva.asr.StreamingRecognitionResult} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.nvidia.riva.asr.StreamingRecognitionResult.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        alternativesList: jspb.Message.toObjectList(
          msg.getAlternativesList(),
          proto.nvidia.riva.asr.SpeechRecognitionAlternative.toObject,
          includeInstance
        ),
        isFinal: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
        stability: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
        channelTag: jspb.Message.getFieldWithDefault(msg, 5, 0),
        audioProcessed: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.nvidia.riva.asr.StreamingRecognitionResult()
  return proto.nvidia.riva.asr.StreamingRecognitionResult.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nvidia.riva.asr.StreamingRecognitionResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.nvidia.riva.asr.SpeechRecognitionAlternative()
        reader.readMessage(value, proto.nvidia.riva.asr.SpeechRecognitionAlternative.deserializeBinaryFromReader)
        msg.addAlternatives(value)
        break
      case 2:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setIsFinal(value)
        break
      case 3:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setStability(value)
        break
      case 5:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setChannelTag(value)
        break
      case 6:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setAudioProcessed(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter()
  proto.nvidia.riva.asr.StreamingRecognitionResult.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nvidia.riva.asr.StreamingRecognitionResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined
  f = message.getAlternativesList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(1, f, proto.nvidia.riva.asr.SpeechRecognitionAlternative.serializeBinaryToWriter)
  }
  f = message.getIsFinal()
  if (f) {
    writer.writeBool(2, f)
  }
  f = message.getStability()
  if (f !== 0.0) {
    writer.writeFloat(3, f)
  }
  f = message.getChannelTag()
  if (f !== 0) {
    writer.writeInt32(5, f)
  }
  f = message.getAudioProcessed()
  if (f !== 0.0) {
    writer.writeFloat(6, f)
  }
}

/**
 * repeated SpeechRecognitionAlternative alternatives = 1;
 * @return {!Array<!proto.nvidia.riva.asr.SpeechRecognitionAlternative>}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.getAlternativesList = function() {
  return /** @type{!Array<!proto.nvidia.riva.asr.SpeechRecognitionAlternative>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.nvidia.riva.asr.SpeechRecognitionAlternative,
    1
  ))
}

/**
 * @param {!Array<!proto.nvidia.riva.asr.SpeechRecognitionAlternative>} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.setAlternativesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.nvidia.riva.asr.SpeechRecognitionAlternative=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nvidia.riva.asr.SpeechRecognitionAlternative}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.addAlternatives = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.nvidia.riva.asr.SpeechRecognitionAlternative,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.clearAlternativesList = function() {
  return this.setAlternativesList([])
}

/**
 * optional bool is_final = 2;
 * @return {boolean}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.getIsFinal = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false))
}

/**
 * @param {boolean} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.setIsFinal = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value)
}

/**
 * optional float stability = 3;
 * @return {number}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.getStability = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.setStability = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value)
}

/**
 * optional int32 channel_tag = 5;
 * @return {number}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.getChannelTag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.setChannelTag = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value)
}

/**
 * optional float audio_processed = 6;
 * @return {number}
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.getAudioProcessed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0))
}

/**
 * @param {number} value
 * @return {!proto.nvidia.riva.asr.StreamingRecognitionResult} returns this
 */
proto.nvidia.riva.asr.StreamingRecognitionResult.prototype.setAudioProcessed = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value)
}

goog.object.extend(exports, proto.nvidia.riva.asr)
